site_name: 'Hacking Notes | Shockz'
site_description: 'Hacking and pentesting notes'
site_author: 'Shockz'


theme:
    name: null
    custom_dir: dark_theme
    # default from mkdocs_theme.yml
    static_templates:
        - 404.html
    include_search_page: true
    search_index_only: true
    history_buttons: true
    article_nav_top: false
    article_nav_bottom: true

nav:
    - Usage: index.md

markdown_extensions:
    - toc:
        permalink: '#'

extra:
    logo: img/avatar.png
    homepage: https://jmlgomez73.github.io